repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.4.0'
  hooks:
  - id: check-merge-conflict
- repo: https://github.com/asottile/yesqa
  rev: v1.5.0
  hooks:
  - id: yesqa
    additional_dependencies:
      - flake8-bandit==4.1.1
      - flake8-bugbear==23.7.10
      - flake8-import-order==0.18.2
      - flake8-requirements==1.7.8
- repo: https://github.com/psf/black
  rev: '23.7.0'
  hooks:
    - id: black
      language_version: python3 # Should be a command that runs python
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.4.0'
  hooks:
  - id: end-of-file-fixer
    exclude: >-
      ^docs/[^/]*\.svg$
  - id: requirements-txt-fixer
  - id: trailing-whitespace
  - id: file-contents-sorter
    files: |
      CONTRIBUTORS.txt|
      docs/spelling_wordlist.txt|
      .gitignore|
      .gitattributes
  - id: check-case-conflict
  - id: check-json
  - id: check-xml
  - id: check-executables-have-shebangs
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: check-added-large-files
  - id: check-symlinks
  - id: debug-statements
  - id: detect-aws-credentials
    args: ['--allow-missing-credentials']
  - id: detect-private-key
    exclude: ^examples/
- repo: https://github.com/PyCQA/flake8
  rev: '6.1.0'
  hooks:
  - id: flake8
    exclude: "^docs/"
    additional_dependencies:
      - flake8-bandit==4.1.1
      - flake8-bugbear==23.7.10
      - flake8-import-order==0.18.2
      - flake8-requirements==1.7.8
- repo: https://github.com/asottile/pyupgrade
  rev: 'v3.10.1'
  hooks:
  - id: pyupgrade
    args: ['--py36-plus']
- repo: https://github.com/Lucas-C/pre-commit-hooks-markup
  rev: v1.0.1
  hooks:
  - id: rst-linter
    files: >-
      ^[^/]+[.]rst$
